Corrections in scripts in pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,8 +49,14 @@ jobs:
           latestJar=$(find . -name "*.jar" | head -n 1)
           echo "Found JAR: $latestJar" 
           cp "$latestJar" app.jar
-          pgrep -f app.jar && pkill -f app.jar || true
+#          pgrep -f app.jar && pkill -f app.jar || true
+          PID=$(pgrep -f "java -jar /home/ubuntu/app/app.jar")
+          if [ -n "$PID" ]; then
+            echo "Killing existing application with PID: $PID"
+            kill $PID
+            sleep 5
+          fi
           nohup java -jar /home/ubuntu/app/app.jar > /home/ubuntu/app/app.log 2>&1 &
           sleep 5
-          ps -ef | grep app.jar
+          pgrep -f app.jar && echo "Application started successfully" || echo "Failed to start application"
 
